## 爱因斯坦求和约定

In [1]:
import torch


In [2]:
a = torch.arange(6).reshape(2, 3)

In [4]:
a

tensor([[0, 1, 2],
        [3, 4, 5]])

### 转置

In [3]:
torch.einsum('ij->ji',[a])

tensor([[0, 3],
        [1, 4],
        [2, 5]])

### 求和

In [6]:
torch.einsum('ij->',[a])

tensor(15)

### 列求和

In [7]:
torch.einsum('ij->j',[a])

tensor([3, 5, 7])

### 哈达玛积

In [8]:
b=torch.arange(6).reshape(2,3)
b

tensor([[0, 1, 2],
        [3, 4, 5]])

In [9]:
torch.einsum('ij,ij->ij',[a,b])

tensor([[ 0,  1,  4],
        [ 9, 16, 25]])

### 点积

In [11]:
b = torch.arange(3)
b

tensor([0, 1, 2])

In [12]:
torch.einsum('ik,k->i',[a,b])

tensor([ 5, 14])

### 外积

In [13]:
a = torch.arange(3)
b = torch.arange(3,7)
torch.einsum('i,j->ij', [a, b])


tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])

In [14]:
a,b

(tensor([0, 1, 2]), tensor([3, 4, 5, 6]))

### test

In [15]:
import torch.nn.functional as F

def random_tensors(shape, num=1, requires_grad=False):
  tensors = [torch.randn(shape, requires_grad=requires_grad) for i in range(0, num)]
  return tensors[0] if num == 1 else tensors

In [16]:
zl = random_tensors([2, 3])

In [17]:
zl

tensor([[-1.0784, -0.3765,  0.3611],
        [ 0.2620, -0.7424, -2.1492]])

In [18]:
W = random_tensors([5, 3, 3], requires_grad=True)

In [19]:
torch.einsum("bk,aki->bai", [zl, W])

tensor([[[-0.5571, -0.2238, -0.8938],
         [-0.2805,  0.4848, -0.2623],
         [ 1.5178,  0.0450, -0.6297],
         [ 1.3036, -0.9711, -1.6246],
         [ 0.7846,  0.5622, -0.7734]],

        [[-0.6270, -3.9375,  4.1081],
         [ 0.7884, -1.8129,  0.0049],
         [ 1.0319, -2.1058,  2.2312],
         [ 3.0491,  0.9635, -0.1343],
         [-1.2554, -3.5111, -2.0805]]], grad_fn=<ViewBackward0>)